### ISSUE TITLE
Pytorch compatibility

### ISSUE THREAD

**Issue by Conchylicultor** [google-research/visu3d#12]
Currently `v3d.DataclassArray` supports TF, Jax and Numpy. It would be great to add Pytorch compatibility too.

As Pytorch has a numpy-like API, it would be fairly easy to add. However there might be some edge cases (as always).

To test Pytorch compatibility, this could be done in multiple steps / PRs:

1) Add `torch` support to `enp.lazy` (`enp.lazy.torch`): https://github.com/google/etils/blob/a307368ae8624000f42c95c8c0abba8e00d13d7d/etils/enp/numpy_utils.py#L39

2) Add `torch` support to `enp.testing.parametrize_xnp`. For backward compatibility, this behavior should be controlled by some global variable (e.g. `enp.testing.set_valid_xnp(['jnp', 'tnp', 'np', 'torch'])`), so users choose which numpy-like modules are supported
https://github.com/google/etils/blob/a307368ae8624000f42c95c8c0abba8e00d13d7d/etils/enp/testing.py#L58

3) Test `torch` support in v3d. Activate torch globally for all tests by creating a [`visu3d/conftest.py` file](https://docs.pytest.org/en/6.2.x/fixture.html#conftest-py-sharing-fixtures-across-multiple-files) which contains `enp.testing.set_valid_xnp(['jnp', 'tnp', 'np', 'torch'])`. Then run all tests with pytest. Because all v3d tests uses `parametrize_xnp`, all tests will be tested agains pytorch.

4) Fix individual tests (starting by `array_dataclass_test`) as I would expect some compatibility issues between torch/xnp.

**Comment by Achint08** [comment]
@Conchylicultor Can I take this up?

**Comment by Conchylicultor** [comment]
> @Conchylicultor Can I take this up?

Yes, of course. I'm not using the asignement on Github but feel free to work on any issue

**Comment by Conchylicultor** [comment]
Pytorch support will be released in the next version
