### ISSUE TITLE
Are the pip wheels broken? Or is my setup missing something? 

### ISSUE THREAD

**Issue by akshay-krishnan** [google-research/visu3d#79]
I do the following in a colab: 
```
!pip install visu3d etils[ecolab] jax[cpu] tf-nightly tfds-nightly sunds
```
and 

```
import numpy as np
import visu3d as v3d
```

and see the following error: 

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-9-a61785c0541a>](https://localhost:8080/#) in <module>
      1 import numpy as np
----> 2 import visu3d as v3d

15 frames
/usr/local/lib/python3.7/dist-packages/dataclass_array/array_dataclass.py in <module>

TypeError: Could not infer typing annotation of _ArrayFieldMetadata defined in dataclass_array.array_dataclass:
 * inner_shape_non_static: 'DynamicShape'
 * dtype: 'Union[array_types.dtypes.DType, type[DataclassArray]]'
'type' object is not subscriptable
```

Not sure if I am missing something.

**Comment by Conchylicultor** [comment]
Thank you for reporting. This was fixed at head but somehow I forgot to trigger a release.
Could you try to update `dataclass_array` once https://github.com/google-research/dataclass_array/pull/18 is submitted ?

For context, this is a breakage in Python 3.7-3.8 when `type[X]` wasn't supported yet.

**Comment by Conchylicultor** [comment]
The fix in `dataclass_array` was released. I'll close this one. Let me know if you still encounter the issue with `v1.2.1`

**Comment by akshay-krishnan** [comment]
Thank you @Conchylicultor , seems to work now!
