### ISSUE TITLE
Custom trace names

### ISSUE THREAD

**Issue by akshay-krishnan** [google-research/visu3d#91]
In the call to make_fig, can we specify the names for each trace? 
For example, different names for different traces instead of the default "Point3d 0, Point3d 1" for points or "Ray 0, Ray 1" for rays. 
This would make the figure more presentable. Is this already possible? If yes, could you please point me to the API reference?

**Comment by Conchylicultor** [comment]
Yes, you can with:

```python
points = points.replace_fig_config(name='My custom name')

v3d.make_fig([points])
```

There's also global config options that can be activated with `v3d.fig_config`, like:

```python
v3d.fig_config.show_zero = False
```

I should update the doc to make this more discoverable.

**Comment by akshay-krishnan** [comment]
Thank you!
That seems to work, except there is a '0' appended to the name like this: 
![image](https://user-images.githubusercontent.com/24805051/212500704-ed45f1fd-b7b9-4ccf-a127-2b4f8f5f9d5e.png)

I had "Left camera" and "Right camera" as the replaced names, not sure how to get rid of the '0'. A section of configuring the plot in the documentation would be nice to have! :)

**Comment by Conchylicultor** [comment]
I agree, this make sense. Sending a fix now and will trigger a release today

**Comment by akshay-krishnan** [comment]
Thank you! I'll try it out once a new release is available. Feel free to close this issue in the meantime.

**Comment by Conchylicultor** [comment]
1.4 is not released: https://github.com/google-research/visu3d/releases/tag/v1.4.0

Let me know if something do not works or you have any feedback!

I've also added a section to customise figures in the https://github.com/google-research/visu3d/blob/main/docs/intro.ipynb
